trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python27:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

# Check if Python is installed
- script: python --version
  displayName: "Check Python Version"

# List all files to check if sum.py exists
- script: ls -l
  displayName: "List Files in Directory"

# Run sum.py and handle potential failures
- script: |
    python sum.py || echo "Python script execution failed"
  displayName: "Run sum.py"

# Run an inline Python script as part of the pipeline
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('This is Section 1 Azure Demonstration')
      print('KL-CSE')
  displayName: "Run Inline Python Script"
